export const ICON_LIST_PROFILE = ["home", "bookmark", "debugger", "logout"];
export const ICON_LIST_COMMON = ["home"];
export const ICON_LIST_HOME_LOGOUT = ["login", "briefcase", "info"];
export const ICON_LIST_HOME_LOGIN = ["user", "briefcase", "info"];
export const FETCH_ALL_JOBS_ENDPOINT = "/api/fetchAllJobs";
export const FETCH_SAVED_JOBS_ENDPOINT = "/api/fetchSavedJobs";
export const SAVE_JOB_ENDPOINT = "/api/saveJob";
export const DELETE_SAVED_JOB_ENDPOINT = "/api/deleteSavedJob";
export const FETCH_USER_ENDPOINT = "/api/fetchUserDetails";
